<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Overlapped</name>
   <tag></tag>
   <elementGuidId>4c2a0dec-6e88-4462-9a76-74bba0170451</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='overlappedButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#overlappedButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ddea4541-5d20-440c-b666-dc197f1fb33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>98fda2f6-a9ca-4963-92d8-166c24d15f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a3d11cc-b173-4928-962d-e90f8aa4f4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>overlappedButton</value>
      <webElementGuid>1eadaf39-2a50-44b6-8aa3-b43f94ad6e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Overlapped</value>
      <webElementGuid>3588b193-51c1-4c1c-bd5d-ed5e5c9b308b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overlappedButton&quot;)</value>
      <webElementGuid>f9b4be2f-cee6-4bc4-b151-cb65b8f6f8be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='overlappedButton']</value>
      <webElementGuid>b904cfad-d1bd-4d88-a922-cae80b55dda9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zero Width'])[1]/following::button[1]</value>
      <webElementGuid>3dcdc50d-62c8-4ce8-be4e-9b22f908149a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Removed'])[1]/following::button[2]</value>
      <webElementGuid>8951dd76-2b12-489c-a58e-3da59be260dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opacity 0'])[1]/preceding::button[1]</value>
      <webElementGuid>9f572c18-1f12-403d-b3ea-1721376fb6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibility Hidden'])[1]/preceding::button[2]</value>
      <webElementGuid>06f5167a-0c09-4c08-8e2c-2aac349088ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Overlapped']/parent::*</value>
      <webElementGuid>8c32922e-755f-4503-9d15-a325652cd2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button</value>
      <webElementGuid>77513462-e0e8-43b6-a77c-b4b976ca9a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'overlappedButton' and (text() = 'Overlapped' or . = 'Overlapped')]</value>
      <webElementGuid>dbd7817f-805d-42b6-a7e2-c50b5194e9bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
