<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserName</name>
   <tag></tag>
   <elementGuidId>9553368d-42fc-4716-87b8-3e693bff5dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c406981c-68cd-a643-3595-8cad5c5c21fd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>837b90f0-150e-4115-af47-96699317a5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>914ffdb3-2ebb-4b1d-98ff-2e526b5c3d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a40d22f-c10d-41fe-beb5-2e5c5510046e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User Name</value>
      <webElementGuid>92364fbf-3ff6-4e7c-9baf-22ede1e40fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>b7ada615-52f2-457c-abc5-6734d9fada6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c406981c-68cd-a643-3595-8cad5c5c21fd</value>
      <webElementGuid>8402cdf6-a75e-48ce-8ce6-9900b4d5289b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c406981c-68cd-a643-3595-8cad5c5c21fd&quot;)</value>
      <webElementGuid>d2770199-7798-47d3-a998-f5a384fdb2b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c406981c-68cd-a643-3595-8cad5c5c21fd']</value>
      <webElementGuid>5ce7a05f-d128-4ea2-a3d1-45bd7248d61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>953bbdd0-d464-455a-b1da-30bc2271de94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'User Name' and @name = 'UserName' and @id = 'c406981c-68cd-a643-3595-8cad5c5c21fd']</value>
      <webElementGuid>7e5078ce-cc62-4a2b-a996-7faab0a80423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
