<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Button That Ignores DOM Click Event</name>
   <tag></tag>
   <elementGuidId>b45baea0-1a5a-483b-a753-0048c35023f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='badButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#badButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0569c2ab-873a-4c04-8255-b48f77a5dad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>42963988-3f92-4f22-90f6-ae9b09ffcdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>badButton</value>
      <webElementGuid>f034e3a4-df3e-4c39-aff5-f71407d5d61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd943795-c45d-4294-86c9-b3f4d6b67ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Button That Ignores DOM Click Event</value>
      <webElementGuid>f864a19a-2348-459f-902e-0d4cd9a9fafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;badButton&quot;)</value>
      <webElementGuid>b0cd6ca2-081d-4007-9588-6394109d92d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='badButton']</value>
      <webElementGuid>10769569-3a8a-4654-8408-2b2e40b99b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Playground'])[1]/following::button[1]</value>
      <webElementGuid>b0c05b2e-7332-42c4-a6f2-bfd50bc3c171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Then execute your test to make sure that it is able to click the button.'])[1]/following::button[1]</value>
      <webElementGuid>17f51682-3619-4680-a156-76de6dd759fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fork the website on GitHub'])[1]/preceding::button[1]</value>
      <webElementGuid>1769f25d-f932-4d2f-8e0b-962fe5f12975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Button That Ignores DOM Click Event']/parent::*</value>
      <webElementGuid>48a8e607-f3ea-4359-bad6-667bc963271b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>1b7ca6cd-196b-4e77-b0ce-1c691fd36b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'badButton' and @type = 'button' and (text() = 'Button That Ignores DOM Click Event' or . = 'Button That Ignores DOM Click Event')]</value>
      <webElementGuid>46a44ae7-e8e1-42bb-bcc0-bc3cb928a4a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
