<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password</name>
   <tag></tag>
   <elementGuidId>92429df7-68ae-4201-8e91-75ff6f2581f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bf50193d-3fdb-0bf4-ceb8-7d8456bd563d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bf50193d-3fdb-0bf4-ceb8-7d8456bd563d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2f20a0d-739c-4e90-b195-d070516f6a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>67fb8aae-70c3-4ae4-adff-a19e2faeab35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e03b56fb-3ce2-41ee-8612-c119add03b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>********</value>
      <webElementGuid>443b3355-1241-47d2-a770-64fcc5584053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>2085e552-1905-433b-9880-52daee13998b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bf50193d-3fdb-0bf4-ceb8-7d8456bd563d</value>
      <webElementGuid>866a2e2d-c725-481f-a6d1-9527099f6ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bf50193d-3fdb-0bf4-ceb8-7d8456bd563d&quot;)</value>
      <webElementGuid>ce237d1c-3a4c-47e7-9da6-a95465fbaa0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bf50193d-3fdb-0bf4-ceb8-7d8456bd563d']</value>
      <webElementGuid>704cb1c6-c0dc-41bc-8b05-a264ebe4806d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>bc419570-0938-4ee1-95b6-c416c806670a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = '********' and @name = 'Password' and @id = 'bf50193d-3fdb-0bf4-ceb8-7d8456bd563d']</value>
      <webElementGuid>b9be2180-bf13-4576-b315-08d906dae86c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
